# Generated by Django 6.1.1 on 2026-09-16 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0002_seed_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('activo', models.BooleanField(default=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='sitios.sitio')),
            ],
        ),
    ]
