# ETAPA 1: Build de la aplicación con Vite
FROM node:20-alpine AS build

WORKDIR /app

# Inyectamos la variable de entorno para la URL de la API de Django
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./
RUN npm install

COPY . .

# Genera los archivos optimizados dentro de /app/dist
RUN npm run build

# ETAPA 2: Servidor de producción con Nginx
FROM nginx:alpine

# Copiamos la carpeta dist generada por Vite hacia Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Configuración personalizada de Nginx para manejar React Router
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]