# Generated by Django 6.1.1 on 2026-09-16 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(blank=True, max_length=30)),
                ('contacto', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='StockElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_elemento', models.CharField(max_length=120)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='proveedores.proveedor')),
            ],
        ),
    ]
