# Generated by Django 6.1.1 on 2026-09-16 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        ('salones', '0002_seed_montajes'),
        ('sitios', '0002_seed_ciudad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('bloqueado', 'Bloqueado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='cotizado', max_length=20)),
                ('fecha_evento', models.DateField()),
                ('validez_oferta', models.DateField(blank=True, null=True)),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('bloqueo_hasta', models.DateTimeField(blank=True, null=True)),
                ('garantia_tipo', models.CharField(blank=True, max_length=30)),
                ('garantia_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('penalizacion_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.cliente')),
                ('montaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='salones.montaje')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='salones.salon')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='sitios.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalogo.concepto')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'confirmado')), fields=('salon', 'fecha_evento'), name='uq_salon_fecha_confirmado'),
        ),
    ]
