# Generated by Django 6.1.1 on 2026-09-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('natural', 'Natural'), ('juridica', 'Jurídica')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('forma_pago', models.CharField(blank=True, max_length=100)),
                ('observaciones_internas', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='hoteles.empresa')),
            ],
        ),
    ]
