# Generated by Django 6.1.1 on 2026-09-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
