# Generated by Django 6.1.1 on 2026-09-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0002_seed_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salones', to='sitios.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='SalonMontaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aforo', models.PositiveIntegerField()),
                ('foto_url', models.URLField(blank=True)),
                ('montaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salones', to='salones.montaje')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montajes', to='salones.salon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('salon', 'montaje'), name='uq_salon_montaje')],
            },
        ),
    ]
