# Generated by Django 6.1.1 on 2026-09-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0002_seed_montajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='foto_url',
            field=models.URLField(blank=True),
        ),
    ]
